### ISSUE TITLE
Configuração do ambiente de trabalho

### ISSUE THREAD

**Issue by araujodavid** [ARiDa/data-science-cookbook#1]
Issue para possíveis dúvidas sobre a configuração do ambiente de trabalho.

**Comment by leolinhares** [comment]
@araujodavid Eu segui suas instruções e instalei tudo corretamente. O jupyter notebook está rodando no browser, mas não sei como eu paro o processo quando não for mais usar. Eu uso o comando `sudo service notebook stop`? O comando vagrant up é só pra configuração inicial?

**Comment by araujodavid** [comment]
@leolinhares para desligar a máquina virtual, e consequentemente o jupyter notebook, basta executar o comando `vagrant halt`. Segue o [link](https://www.vagrantup.com/docs/cli/) para a command-line interface do Vagrant.

**Comment by israelcvidal** [comment]
@araujodavid , você já descobriu como consertar o problema da Falha de Autenticação? Não consigo fazer funcionar no meu computador!

**Comment by araujodavid** [comment]
@israelcvidal qual o erro específico?

**Comment by israelcvidal** [comment]
@araujodavid 
![captura de tela 2016-10-05 as 08 03 26](https://cloud.githubusercontent.com/assets/8698423/19110769/4d83a170-8ad2-11e6-8ced-d62ba4fd28b1.png)

Eu até já apaguei todas as ssh do computador e gerei uma nova pra ver se mudava alguma coisa, mas continua na mesma...

**Comment by araujodavid** [comment]
@israelcvidal executa o `vagrant halt`, descomenta a linha 134 do seu Vagrantfile para `vb.gui = true` e executa novamente o `vagrant up`. Isso irá habilitar a interface da máquina virtual e a gente terá uma ideia melhor do problema, caso peça pra você fazer login entre com vagrant:vagrant. Faça isso e veja se dará certo por favor.

**Comment by israelcvidal** [comment]
@araujodavid continua acontecendo a mesma coisa. No terminal da VM ele pede pra digitar o login e a senha, depois que digito tudo continua igual. Ele diz que está logado e não mostra nenhuma mensagem de erro, enquanto no terminal host ele continua dando falha de autenticação.

**Comment by araujodavid** [comment]
@israelcvidal você está com as versões mais novas do VirtualBox e Vagrant? Tenta rodar usando o `vagrant up --debug` para vermos que conseguimos pegar um erro mais específico.
