### ISSUE TITLE
Trabalho 2 - Stemming

### ISSUE THREAD

**Issue by leopoldosmj** [ARiDa/data-science-cookbook#3]
Caros, bom dia.

É necessário instalar o NLTK na VM para realizar o Stemming (pré-processamento do trabalho 2)?

Grato,
Leopoldo Melo

**Comment by lucaspg96** [comment]
Sim, assim como os pacotes de stopwords e stemmer

Enviado pelo meu Windows Phone

---

De: leopoldosmjmailto:notifications@github.com
Enviada em: ‎18/‎11/‎2016 01:01
Para: ARiDa/data-science-cookbookmailto:data-science-cookbook@noreply.github.com
Assunto: [ARiDa/data-science-cookbook] Trabalho 2 - Stemming (#3)

Caros, bom dia.

E necess?rio instalar o NLTK na VM para realizar o Stemming (pré-processamento do trabalho 2)?

Grato,
Leopoldo Melo

**Comment by araujodavid** [comment]
Exatamente @leopoldosmj, precisa instalar usando o pip via SSH na VM do Vagrant.

**Comment by holandajunior** [comment]
Se ajudar @leopoldosmj, pode seguir:

Acessa máquina via ssh e execute o comando:
pip install nltk

Após isso, você terá o nltk instalado. Ainda, execute um notebook com os
seguintes comandos:

import nltk
nltk.download()

e siga as instruções para instalar os pacotes de tokenizer, stemming e
stopwords. Para facilitar, baixa o pacote 'books' e 'rslp'. Para uma melhor
instrução, pode seguir a documentação: http://www.nltk.org/book/ch01.html

2016-11-18 7:36 GMT-03:00 David Araújo notifications@github.com:

**Comment by leopoldosmj** [comment]
Obrigado, pessoal!
